#!/bin/bash

tofi_command="tofi"
uptime=$(uptime -p | sed -e 's/up //g')

## Entries
shutdown="H -> Shutdown"
reboot="J -> Restart"
lock="L -> Lock"
suspend="K -> Sleep"
logout="Q -> Logout"

# Ask for confirmation
cdialog() {
	yad --title='Confirm?' --borders=15 --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="Are you sure?" --text-align=center
}

# Variable passed to rofi
open_menu() {
	options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

	chosen="$(echo -e "$options" | $tofi_command --prompt "UP - $uptime --> ")"
	case $chosen in
	$shutdown)
		cdialog
		if [[ "$?" == 0 ]]; then
			systemctl poweroff
		else
			exit
		fi
		;;
	$reboot)
		cdialog
		if [[ "$?" == 0 ]]; then
			systemctl reboot
		else
			exit
		fi
		;;
	$lock)
		~/.config/hypr/scripts/lockscreen
		;;
	$suspend)
		cdialog
		if [[ "$?" == 0 ]]; then
			# mpc -q pause
			pamixer -m
			~/.config/hypr/scripts/lockscreen
			systemctl suspend
		else
			exit
		fi
		;;
	$logout)
		cdialog
		if [[ "$?" == 0 ]]; then
			kill -9 -1
		else
			exit
		fi
		;;
	esac
}

if [[ ! $(pidof tofi) ]]; then
	open_menu
else
	pkill tofi
fi
