# Edit navigation
abbr -a home --position anywhere '$HOME/'
# Navigation
abbr -a tmp '$HOME/.tmp'
abbr -a temp '$HOME/.tmp'
abbr -a down 'z k dlds'
abbr -a downs 'z $HOME/Downloads/'
abbr -a docs 'z $HOME/Documents/'
abbr -a pics 'z $HOME/Pictures/'
abbr -a desk 'z $HOME/Desktop/'
abbr -a memes 'z $HOME/Pictures/memes'
abbr -a nts 'z $HOME/nts/'
abbr -a ... 'cd ../../ && ls'
abbr -a .... 'cd ../../../ && ls'
# abbr -a play '$HOME/src/PLAYGROUND/ && ls'
abbr -a src 'cd $HOME/src/school'
# abbr -a scr 'z src scr'
abbr -a priv 'z .private'
abbr -a dox 'cd $HOME/movies/dox'
# abbr -a k 'cd $HOME/k'
abbr -a dlds 'cd $HOME/dlds && eza'
abbr -a pics 'cd $HOME/Pictures'
abbr -a prts 'clear -x; j $HOME/prts; eza -F --sort newest -1'
abbr -a sec 'cd $HOME/k/sec'
# abbr -a fifu 'z .co fish func'
abbr -a fico 'z .co fish conf'
abbr -a ab 'cd_abbrs_and_chezmoi_add'
abbr -a fun 'cd_funcs_and_chezmoi_add'
abbr -a root 'cd / && clear'
abbr -a baks '$HOME/.backup'
abbr -a ses 'cd $HOME/.config/kitty/ses'
abbr -a cdr 'cd /'
abbr -a me 'clear -x && cd $HOME/me && ls'
abbr -a cd.. 'cd ..'
# abbr -a one ' clear -x && jj $HOME onedrive && eza -lFsmodified'
abbr -a bib 'jj $HOME/bible'
# tmp
# abbr -a selw 'cd $WORK_PATH && sel blob.py experiment.py initialize_blobs.py setup_plot.py'
# abbr -a works "clear -x && cd $WORK_PATH && sel blob.py experiment.py initialize_blobs.py setup_plot.py"


# self
abbr -a josie '$HOME/me/self/josie'
abbr -a mams '$HOME/me/self/mams'
abbr -a obs '$HOME/nts/obs'


# cme (eza --sort modified --reverse | fzf)
abbr -a movs 'cd $HOME/movies'
abbr -a shorts 'cd $HOME/movies/shorts'
abbr -a baks 'cd /media/sdb1-usb-Generic_MassStor && ls'
abbr -a react 'cd $HOME/src/react/max-react-tutorial'
abbr -a reactv 'cd $HOME/movies/react_tutorial/THIS_The.Ultimate.React.Course.2023_React.Redux.And.More'
abbr -a dok 'cd $HOME/Documents'
abbr -a cv '$HOME/Documents/CV_PB/src/new'
