# qb
abbr -a qb 'qutebrowser &;disown'
abbr -a qbh 'qutebrowser --help'
abbr -a qbr 'qutebrowser -r <SESSION> &;disown'
abbr -a qp 'qbpm'
abbr -a qpcd 'z ~/k qute-profiles'
abbr -a qpc 'qbpm choose -m "tofi --prompt-text qutebrowser --config $HOME/.config/tofi/tofi-qbpm"'
abbr -a qpe 'qbpm edit'
abbr -a qpr 'qbpm launch'
abbr -a qpls 'qbpm list'
abbr -a qpn 'qbpm new'
abbr -a qpp 'cd $HOME/k/qute-profiles'
abbr -a qpf 'qbpm from-session'
abbr -a qmarks 'cd ~/ && jj .conf qutebrowser && vi quickmarks'
abbr -a qutelap 'hyprctl dispatch exec QT_AUTO_SCREEN_SCALE_FACTOR=2 QT_SCALE_FACTOR=1.3 qutebrowser'
abbr -a per 'hyprctl dispatch exec qbpm launch perplexity;disown;exit'
abbr -a phi 'hyprctl dispatch exec qbpm launch phind;disown;exit'
abbr -a playall 'for file in (ls *.mp4);kitten @ launch qutebrowser (realpath $file);end;'
