abbr -a ryi 'rye init'
abbr -a ryp 'rye pin'
abbr -a rya 'rye add'
abbr -a ryl 'rye list'
abbr -a ryrec 'rye make-req'
abbr -a ryrm 'rye remove '
abbr -a ryr 'rye run '
abbr -a rys 'rye sync '
abbr -a rycat 'rye show'
