# scripts
abbr -a cam '/home/tildavimer/src/scripts/alone/cam.fish'
abbr -a cam1 'nohup mpv av://v4l2:/dev/video4 --profile=low-latency --untimed --no-terminal &'
abbr -a tryfun '/home/tildavimer/tmp/fish_script_test.fish'
abbr -a tryfunedit 'nvim /home/tildavimer/tmp/fish_script_test.fish'
abbr -a leo 'exec $HOME/src/scripts/alone/leovegas.fish'
abbr -a nscr 'script-skeleton-structure'
abbr -a scra 'script-skeleton-structure'
abbr -a scr '$HOME/src/scripts'
abbr -a cdscra 'z $HOME/src/scripts && script-skeleton-structure'
