# taskbook
abbr -a kk 'clear -x && taskbook'
abbr -a kkb 'taskbook --begin'
abbr -a kkc 'taskbook --check'
abbr -a kkcc 'taskbook --clear'
abbr -a kky 'taskbook --copy'
abbr -a kkd 'taskbook --delete'
abbr -a kke 'taskbook --edit'
abbr -a kkf 'taskbook --find'
abbr -a kkh 'taskbook --help'
abbr -a kkl 'taskbook --list'
abbr -a kkm 'taskbook --move'
abbr -a kkn 'taskbook --note'
abbr -a kkp 'taskbook --priority'
abbr -a kkr 'taskbook --restore'
abbr -a kks 'taskbook --star'
abbr -a kka 'taskbook --task'
abbr -a kkaa 'taskbook --archive'
abbr -a kkti 'taskbook --timeline'
abbr -a kkv 'taskbook --version'

