plugins = [
    # Installs the plugin from https://github.com/Duckonaut/split-monitor-workspaces
    "Duckonaut/split-monitor-workspaces",
    # A more explicit definition of the git install
    # { git = "https://github.com/Duckonaut/split-monitor-workspaces", branch = "main", name = "split-monitor-workspaces" },
    # Installs the same plugin from a local folder
    # { local = "/home/duckonaut/repos/split-monitor-workspaces" },
    # "zakk4223/hyprNStack",
    # { local = "https://github.com/zakk4223/hyprNStack", branch = "main", name = "hyprNStack" },
]
